library(tm)
library(SnowballC)
library(wordcloud)

gf = read.csv('GF.csv', stringsAsFactors = FALSE)
gfCorpus <- Corpus(VectorSource(gf[,30]))
gfCorpus <- tm_map(gfCorpus, PlainTextDocument)
gfCorpus <- tm_map(gfCorpus, content_transformer(tolower), lazy = T)
gfCorpus <- tm_map(gfCorpus, removePunctuation, lazy = T)
gfCorpus <- tm_map(gfCorpus, removeWords, stopwords('english'), lazy = T)
gfCorpus <- tm_map(gfCorpus, stemDocument, lazy = T)
pal2 <- brewer.pal(12,"Paired")
wordcloud(gfCorpus, max.words = 100, random.order = FALSE, colors = pal2)
